In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
import os

In [24]:
human = os.listdir("./human")
bot = os.listdir("./bot")

data = pd.read_csv("./human/" + human[0])
data = data.drop("Unnamed: 0", axis=1)
[data[x].unique() for x in ["button", "click", "key", "press"]]

[array([nan, True], dtype=object),
 array([nan, True, False], dtype=object),
 array([nan, 'a', 's', ')', '8', ':', 'V', '/', 'N', 'c', 'L', 'C', '=',
        '+', '}', ']', 'w', 't', '>', 'f', 'd', '-', "'", 'p', 'v', '(',
        'Q', 'W', 'K', 'A', 'l', 'i', 'x', '{', 'S', 'm', 'X', 'b', 'Z',
        'E', '!', 'J'], dtype=object),
 array([nan, True, False], dtype=object)]